# Generated by Django 6.0.6 on 2026-06-09 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_attivo', models.BooleanField(default=False, help_text='Se attivo, abilita le pagine di debug Django in produzione.', verbose_name='debug attivo')),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostazioni_aggiornate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impostazioni sistema',
                'verbose_name_plural': 'Impostazioni sistema',
            },
        ),
    ]
