# Generated by Django 6.0.6 on 2026-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_ruolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='codice fiscale'),
        ),
    ]
