# Generated by Django 6.0.6 on 2026-07-14 07:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria corso',
                'verbose_name_plural': 'Categorie corso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CorsoAcademy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('durata_ore', models.PositiveIntegerField()),
                ('obbligatorio', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corsi', to='academy.categoriacorso')),
            ],
            options={
                'verbose_name': 'Corso Academy',
                'verbose_name_plural': 'Corsi Academy',
                'ordering': ['titolo'],
            },
        ),
        migrations.CreateModel(
            name='AssegnazioneCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assegnazione', models.DateField(default=datetime.date.today)),
                ('data_scadenza', models.DateField()),
                ('stato', models.CharField(choices=[('ASSEGNATO', 'Assegnato'), ('COMPLETATO', 'Completato'), ('SCADUTO', 'Scaduto'), ('ANNULLATO', 'Annullato')], default='ASSEGNATO', max_length=20)),
                ('data_completamento', models.DateField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to=settings.AUTH_USER_MODEL)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni', to='academy.corsoacademy')),
            ],
            options={
                'verbose_name': 'Assegnazione corso',
                'verbose_name_plural': 'Assegnazioni corso',
                'ordering': ['-data_assegnazione', '-id'],
            },
        ),
    ]
